import { DivSuggestion } from "./divKeywords";

/**
 * App-specific keywords, primitives, and API suggestions for WXDIV 3.0 Apps
 */
export const APP_AUTOCOMPLETE_ITEMS: DivSuggestion[] = [
  // 1. UI PRIMITIVES
  {
    name: "draw_button",
    type: "function",
    description: "Dibuja un botón interactivo en pantalla con texto, estilo y callback onClick.",
    syntax: "draw_button(x, y, w, h, 'Guardar', onClickCallback);",
    insertText: "draw_button(${1:x}, ${2:y}, ${3:120}, ${4:36}, \"${5:Guardar}\", ${6:callback});",
    categoryLabel: "UI Primitiva",
  },
  {
    name: "draw_input",
    type: "function",
    description: "Crea un campo de entrada de texto interactivo con valor reactivo y onChange.",
    syntax: "draw_input(x, y, w, h, valor, onChangeCallback, placeholder);",
    insertText: "draw_input(${1:x}, ${2:y}, ${3:200}, ${4:36}, ${5:valor}, ${6:onChange}, \"${7:Escribe aquí...}\");",
    categoryLabel: "UI Primitiva",
  },
  {
    name: "draw_select",
    type: "function",
    description: "Menú desplegable interactivo con lista de opciones y valor seleccionado.",
    syntax: "draw_select(x, y, w, h, opciones, seleccionado, onChangeCallback);",
    insertText: "draw_select(${1:x}, ${2:y}, ${3:160}, ${4:36}, [\"Opción A\", \"Opción B\"], ${5:seleccionado}, ${6:onChange});",
    categoryLabel: "UI Primitiva",
  },
  {
    name: "draw_table",
    type: "function",
    description: "Renderiza una tabla de datos estructurada con columnas, filas y estilo responsive.",
    syntax: "draw_table(x, y, w, h, columnas, filas);",
    insertText: "draw_table(${1:x}, ${2:y}, ${3:400}, ${4:220}, [\"ID\", \"Nombre\", \"Estado\"], ${5:filas});",
    categoryLabel: "UI Primitiva",
  },
  {
    name: "draw_modal",
    type: "function",
    description: "Muestra una ventana modal flotante con título, cuerpo de contenido y botón cerrar.",
    syntax: "draw_modal(x, y, w, h, 'Título', 'Contenido descriptivo', onCloseCallback);",
    insertText: "draw_modal(${1:100}, ${2:80}, ${3:440}, ${4:300}, \"${5:Confirmar}\", \"${6:¿Deseas continuar?}\", ${7:onClose});",
    categoryLabel: "UI Primitiva",
  },
  {
    name: "draw_tabs",
    type: "function",
    description: "Barra de pestañas horizontales para alternar entre diferentes vistas o secciones.",
    syntax: "draw_tabs(x, y, w, h, tabs, activeTab, onTabChangeCallback);",
    insertText: "draw_tabs(${1:x}, ${2:y}, ${3:400}, ${4:36}, [\"General\", \"Ajustes\", \"Datos\"], ${5:activeTab}, ${6:onTabChange});",
    categoryLabel: "UI Primitiva",
  },

  // 2. LAYOUT SYSTEM
  {
    name: "layout_begin",
    type: "function",
    description: "Inicia un contenedor de disposición automática (vertical, horizontal o grid con gap).",
    syntax: "layout_begin('vertical', x, y, width, height, gap, padding);",
    insertText: "layout_begin(\"vertical\", ${1:20}, ${2:60}, ${3:320}, ${4:400}, ${5:10}, ${6:12});\n  ${0}\nlayout_end();",
    categoryLabel: "Layout",
  },
  {
    name: "layout_next",
    type: "function",
    description: "Obtiene las coordenadas calculadas (x, y, w, h) para el siguiente elemento del layout.",
    syntax: "var pos = layout_next(w, h);",
    insertText: "layout_next(${1:width}, ${2:height});",
    categoryLabel: "Layout",
  },
  {
    name: "layout_end",
    type: "function",
    description: "Cierra el contenedor de disposición actual.",
    syntax: "layout_end();",
    insertText: "layout_end();",
    categoryLabel: "Layout",
  },

  // 3. STATE MANAGEMENT & STORE
  {
    name: "STORE",
    type: "keyword",
    description: "Declara un almacén de estado reactivo global para la aplicación.",
    syntax: "STORE user\n  nombre: string = ''\n  email: string = ''\n  logged: bool = false\nEND",
    insertText: "STORE ${1:store_name}\n  ${2:key}: ${3:value}\nEND",
    categoryLabel: "Estado Reactivo",
  },
  {
    name: "store_get",
    type: "function",
    description: "Lee un valor del almacén de estado reactivo por su ruta/clave.",
    syntax: "var valor = store_get('user.nombre');",
    insertText: "store_get(\"${1:user.nombre}\");",
    categoryLabel: "Estado Reactivo",
  },
  {
    name: "store_set",
    type: "function",
    description: "Actualiza una propiedad en el almacén de estado y dispara observadores reactivos.",
    syntax: "store_set('user.logged', true);",
    insertText: "store_set(\"${1:key}\", ${2:value});",
    categoryLabel: "Estado Reactivo",
  },
  {
    name: "onDataChange",
    type: "function",
    description: "Registra un listener reactivo cuando cambia una propiedad específica del store.",
    syntax: "onDataChange('user.logged', function(valor) { ... });",
    insertText: "onDataChange(\"${1:key}\", function(val) {\n  ${0}\n});",
    categoryLabel: "Eventos App",
  },
  {
    name: "ON",
    type: "keyword",
    description: "Observador reactivo: ejecuta un bloque cuando una condición del estado se cumple.",
    syntax: "ON user.logged == true\n  navigate('dashboard');\nEND",
    insertText: "ON ${1:condicion}\n  ${0}\nEND",
    categoryLabel: "Estado Reactivo",
  },

  // 4. ROUTER & EVENT SYSTEM
  {
    name: "navigate",
    type: "function",
    description: "Cambia la ruta activa de la aplicación (ej. 'login', 'dashboard', 'settings').",
    syntax: "navigate('dashboard');",
    insertText: "navigate(\"${1:dashboard}\");",
    categoryLabel: "Router",
  },
  {
    name: "onRouteChange",
    type: "function",
    description: "Escucha transiciones de ruta para inicializar vistas o cargar datos.",
    syntax: "onRouteChange(function(newRoute) { ... });",
    insertText: "onRouteChange(function(route) {\n  ${0}\n});",
    categoryLabel: "Router",
  },
  {
    name: "onClick",
    type: "function",
    description: "Vincula un callback de clic a un elemento o identificador de la interfaz.",
    syntax: "onClick('btn_guardar', function() { ... });",
    insertText: "onClick(\"${1:elementId}\", function() {\n  ${0}\n});",
    categoryLabel: "Eventos App",
  },
  {
    name: "onSubmit",
    type: "function",
    description: "Captura el envío de un formulario de datos.",
    syntax: "onSubmit('form_login', function(data) { ... });",
    insertText: "onSubmit(\"${1:formId}\", function(data) {\n  ${0}\n});",
    categoryLabel: "Eventos App",
  },

  // 5. DATA PERSISTENCE & NETWORKING
  {
    name: "save_json",
    type: "function",
    description: "Guarda un objeto o estructura de datos en almacenamiento local persistente.",
    syntax: "save_json('config.json', config);",
    insertText: "save_json(\"${1:archivo.json}\", ${2:objeto});",
    categoryLabel: "Persistencia",
  },
  {
    name: "load_json",
    type: "function",
    description: "Recupera un archivo o clave JSON persistida en almacenamiento local.",
    syntax: "var config = load_json('config.json', valorPorDefecto);",
    insertText: "load_json(\"${1:archivo.json}\", ${2:valorPorDefecto});",
    categoryLabel: "Persistencia",
  },
  {
    name: "load_sqlite",
    type: "function",
    description: "Abre o inicializa una base de datos relacional SQLite/IndexedDB para la app.",
    syntax: "load_sqlite('app.db');",
    insertText: "load_sqlite(\"${1:app.db}\");",
    categoryLabel: "Persistencia",
  },
  {
    name: "sqlite_query",
    type: "function",
    description: "Ejecuta una consulta SQL (SELECT, INSERT, UPDATE, DELETE) sobre la base de datos.",
    syntax: "var filas = sqlite_query('SELECT * FROM clientes WHERE activo = 1');",
    insertText: "sqlite_query(\"${1:SELECT * FROM tabla}\");",
    categoryLabel: "Persistencia",
  },
  {
    name: "fetch_api",
    type: "function",
    description: "Realiza una petición HTTP asíncrona a un servicio web o API REST.",
    syntax: "fetch_api('https://api.ejemplo.com/data', { method: 'GET' }, callback);",
    insertText: "fetch_api(\"${1:https://api.ejemplo.com/data}\", { method: \"${2:GET}\" }, function(res, err) {\n  ${0}\n});",
    categoryLabel: "Red & APIs",
  },
  {
    name: "auth_login",
    type: "function",
    description: "Gestiona autenticación de usuario, genera sesión local y token seguro.",
    syntax: "auth_login(email, password, callback);",
    insertText: "auth_login(${1:email}, ${2:password}, function(user, err) {\n  ${0}\n});",
    categoryLabel: "Seguridad",
  },
  {
    name: "auth_logout",
    type: "function",
    description: "Cierra la sesión del usuario actual y limpia las credenciales del almacén.",
    syntax: "auth_logout();",
    insertText: "auth_logout();",
    categoryLabel: "Seguridad",
  },
];
