export type SuggestionType = "keyword" | "function" | "variable" | "constant" | "type";

export interface DivSuggestion {
  name: string;
  type: SuggestionType;
  description: string;
  syntax?: string;
  insertText?: string;
  categoryLabel?: string;
}

export const DIV_AUTOCOMPLETE_ITEMS: DivSuggestion[] = [
  // PALABRAS CLAVE PRINCIPALES DE CONTROL Y PROCESO
  {
    name: "PROCESS",
    type: "keyword",
    description: "Declara un nuevo proceso o entidad independiente en DIV Games Studio.",
    syntax: "PROCESS nombre(parámetros)\nBEGIN\n  LOOP\n    FRAME;\n  END\nEND",
    insertText: "PROCESS ",
    categoryLabel: "Palabra clave",
  },
  {
    name: "BEGIN",
    type: "keyword",
    description: "Marca el inicio del bloque ejecutable de un proceso o programa.",
    syntax: "BEGIN\n  // código\nEND",
    insertText: "BEGIN\n  ",
    categoryLabel: "Palabra clave",
  },
  {
    name: "END",
    type: "keyword",
    description: "Cierra un bloque de código, bucle, estructura condicional o proceso.",
    syntax: "END",
    insertText: "END",
    categoryLabel: "Palabra clave",
  },
  {
    name: "FRAME",
    type: "keyword",
    description: "Cede el control del proceso al motor por un fotograma (60 FPS).",
    syntax: "FRAME;\n// o FRAME(porcentaje);",
    insertText: "FRAME;",
    categoryLabel: "Palabra clave",
  },
  {
    name: "LOCAL",
    type: "keyword",
    description: "Declara variables locales que cada proceso posee de forma independiente.",
    syntax: "LOCAL\n  int mi_variable;\n  string nombre;",
    insertText: "LOCAL\n  ",
    categoryLabel: "Palabra clave",
  },
  {
    name: "PRIVATE",
    type: "keyword",
    description: "Declara variables privadas exclusivas de la definición del proceso actual.",
    syntax: "PRIVATE\n  int vida = 100;\n  int velocidad = 4;",
    insertText: "PRIVATE\n  ",
    categoryLabel: "Palabra clave",
  },
  {
    name: "GLOBAL",
    type: "keyword",
    description: "Declara variables globales accesibles desde cualquier proceso o función.",
    syntax: "GLOBAL\n  int puntuacion = 0;\n  int record = 9999;",
    insertText: "GLOBAL\n  ",
    categoryLabel: "Palabra clave",
  },
  {
    name: "PROGRAM",
    type: "keyword",
    description: "Encabezado y nombre del programa o videojuego principal.",
    syntax: "PROGRAM mi_juego;\nBEGIN\n  // inicio\nEND",
    insertText: "PROGRAM ",
    categoryLabel: "Palabra clave",
  },
  {
    name: "LOOP",
    type: "keyword",
    description: "Bucle infinito principal donde se ejecutan los ciclos de vida del proceso.",
    syntax: "LOOP\n  // lógica por fotograma\n  FRAME;\nEND",
    insertText: "LOOP\n    FRAME;\n  END",
    categoryLabel: "Palabra clave",
  },
  {
    name: "WHILE",
    type: "keyword",
    description: "Bucle condicional: se repite mientras la expresión sea verdadera.",
    syntax: "WHILE (condicion)\n  // código\n  FRAME;\nEND",
    insertText: "WHILE ()",
    categoryLabel: "Palabra clave",
  },
  {
    name: "REPEAT",
    type: "keyword",
    description: "Bucle que ejecuta al menos una vez hasta que la condición UNTIL se cumpla.",
    syntax: "REPEAT\n  // código\n  FRAME;\nUNTIL (condicion);",
    insertText: "REPEAT\n  FRAME;\nUNTIL ();",
    categoryLabel: "Palabra clave",
  },
  {
    name: "UNTIL",
    type: "keyword",
    description: "Condición de parada para el bucle REPEAT.",
    syntax: "UNTIL (condicion);",
    insertText: "UNTIL ()",
    categoryLabel: "Palabra clave",
  },
  {
    name: "FOR",
    type: "keyword",
    description: "Bucle con contador estándar de iteraciones.",
    syntax: "FOR (i = 0; i < 10; i++)\n  // código\nEND",
    insertText: "FOR (i = 0; i < 10; i++)\n    \n  END",
    categoryLabel: "Palabra clave",
  },
  {
    name: "FROM",
    type: "keyword",
    description: "Bucle estilo Pascal/DIV con rango inicial y límite TO.",
    syntax: "FROM i = 0 TO 10 STEP 1\n  // código\nEND",
    insertText: "FROM i = 0 TO 10\n    \n  END",
    categoryLabel: "Palabra clave",
  },
  {
    name: "TO",
    type: "keyword",
    description: "Define el límite superior en bucles FROM.",
    syntax: "FROM x = 1 TO 100",
    insertText: "TO ",
    categoryLabel: "Palabra clave",
  },
  {
    name: "STEP",
    type: "keyword",
    description: "Especifica el incremento de paso en bucles FROM ... TO.",
    syntax: "STEP 2",
    insertText: "STEP ",
    categoryLabel: "Palabra clave",
  },
  {
    name: "IF",
    type: "keyword",
    description: "Estructura condicional básica de DIV Games Studio.",
    syntax: "IF (condicion)\n  // código si es verdadero\nEND",
    insertText: "IF ()\n    \n  END",
    categoryLabel: "Palabra clave",
  },
  {
    name: "ELSE",
    type: "keyword",
    description: "Bloque alternativo de una sentencia IF cuando no se cumple la condición.",
    syntax: "ELSE\n  // código alternativo",
    insertText: "ELSE\n    ",
    categoryLabel: "Palabra clave",
  },
  {
    name: "ELSIF",
    type: "keyword",
    description: "Condición secundaria encadenada en sentencias IF.",
    syntax: "ELSIF (otra_condicion)\n  // código",
    insertText: "ELSIF ()\n    ",
    categoryLabel: "Palabra clave",
  },
  {
    name: "SWITCH",
    type: "keyword",
    description: "Estructura de bifurcación múltiple según el valor de una variable.",
    syntax: "SWITCH (variable)\n  CASE 1: ... END\n  DEFAULT: ... END\nEND",
    insertText: "SWITCH ()\n  CASE 1:\n    \n    END\nEND",
    categoryLabel: "Palabra clave",
  },
  {
    name: "CASE",
    type: "keyword",
    description: "Rama de valor en una estructura SWITCH.",
    syntax: "CASE valor:\n  // código\nEND",
    insertText: "CASE :",
    categoryLabel: "Palabra clave",
  },
  {
    name: "DEFAULT",
    type: "keyword",
    description: "Rama predeterminada cuando ningún CASE coincide en un SWITCH.",
    syntax: "DEFAULT:\n  // código por defecto\nEND",
    insertText: "DEFAULT:\n    ",
    categoryLabel: "Palabra clave",
  },
  {
    name: "BREAK",
    type: "keyword",
    description: "Interrumpe inmediatamente la ejecución de un bucle o bloque SWITCH.",
    syntax: "BREAK;",
    insertText: "BREAK;",
    categoryLabel: "Palabra clave",
  },
  {
    name: "CONTINUE",
    type: "keyword",
    description: "Salta directamente al siguiente ciclo de una estructura iterativa.",
    syntax: "CONTINUE;",
    insertText: "CONTINUE;",
    categoryLabel: "Palabra clave",
  },
  {
    name: "RETURN",
    type: "keyword",
    description: "Retorna un valor desde una función o proceso.",
    syntax: "RETURN resultado;",
    insertText: "RETURN ",
    categoryLabel: "Palabra clave",
  },
  {
    name: "CONST",
    type: "keyword",
    description: "Bloque de declaración de constantes inmutables.",
    syntax: "CONST\n  MAX_VIDAS = 3;\n  GRAVEDAD = 1;",
    insertText: "CONST\n  ",
    categoryLabel: "Palabra clave",
  },
  {
    name: "TYPE",
    type: "keyword",
    description: "Identificador del tipo de proceso para colisiones y señales.",
    syntax: "TYPE nombre_proceso",
    insertText: "TYPE ",
    categoryLabel: "Palabra clave",
  },
  {
    name: "STRUCT",
    type: "keyword",
    description: "Declara una estructura de datos personalizada con múltiples campos.",
    syntax: "STRUCT mi_estructura\n  int id;\n  int estado;\nEND",
    insertText: "STRUCT ",
    categoryLabel: "Palabra clave",
  },
  {
    name: "FUNCTION",
    type: "keyword",
    description: "Declara una función que retorna un valor sin crear un proceso independiente.",
    syntax: "FUNCTION sumar(a, b)\nBEGIN\n  RETURN a + b;\nEND",
    insertText: "FUNCTION ",
    categoryLabel: "Palabra clave",
  },
  {
    name: "CLONE",
    type: "keyword",
    description: "Crea una copia o clon exacto del proceso actual en memoria.",
    syntax: "CLONE",
    insertText: "CLONE",
    categoryLabel: "Palabra clave",
  },
  {
    name: "ONEXIT",
    type: "keyword",
    description: "Bloque de código que se ejecuta cuando el proceso es eliminado o termina.",
    syntax: "ONEXIT\n  // liberar recursos\nEND",
    insertText: "ONEXIT\n    \n  END",
    categoryLabel: "Palabra clave",
  },

  // TIPOS DE DATOS
  {
    name: "INT",
    type: "type",
    description: "Tipo de variable número entero de 32 bits con signo.",
    syntax: "INT mi_entero = 0;",
    insertText: "INT ",
    categoryLabel: "Tipo de dato",
  },
  {
    name: "BYTE",
    type: "type",
    description: "Tipo de variable entero de 8 bits sin signo (0 a 255).",
    syntax: "BYTE color_idx = 15;",
    insertText: "BYTE ",
    categoryLabel: "Tipo de dato",
  },
  {
    name: "WORD",
    type: "type",
    description: "Tipo de variable entero de 16 bits sin signo (0 a 65535).",
    syntax: "WORD valor = 1000;",
    insertText: "WORD ",
    categoryLabel: "Tipo de dato",
  },
  {
    name: "STRING",
    type: "type",
    description: "Tipo de variable para cadenas de texto.",
    syntax: "STRING texto = \"Hola DIV\";",
    insertText: "STRING ",
    categoryLabel: "Tipo de dato",
  },
  {
    name: "FLOAT",
    type: "type",
    description: "Tipo de variable número real de coma flotante.",
    syntax: "FLOAT velocidad = 3.14;",
    insertText: "FLOAT ",
    categoryLabel: "Tipo de dato",
  },

  // FUNCIONES BUILTIN POPULARES DE DIV GAMES STUDIO
  {
    name: "set_mode",
    type: "function",
    description: "Establece la resolución de la pantalla gráfica (ej. m640x480, m320x200).",
    syntax: "set_mode(m640x480);",
    insertText: "set_mode(m640x480);",
    categoryLabel: "Función DIV",
  },
  {
    name: "set_fps",
    type: "function",
    description: "Ajusta la tasa de fotogramas por segundo del motor (ej. 60 o 30).",
    syntax: "set_fps(60, 0);",
    insertText: "set_fps(60, 0);",
    categoryLabel: "Función DIV",
  },
  {
    name: "load_fpg",
    type: "function",
    description: "Carga un archivo de gráficos FPG en memoria y devuelve su identificador de archivo.",
    syntax: "file = load_fpg(\"graficos.fpg\");",
    insertText: "load_fpg(\"\")",
    categoryLabel: "Función DIV",
  },
  {
    name: "load_map",
    type: "function",
    description: "Carga un mapa o imagen individual MAP en el archivo gráfico.",
    syntax: "graph = load_map(\"fondo.map\");",
    insertText: "load_map(\"\")",
    categoryLabel: "Función DIV",
  },
  {
    name: "collision",
    type: "function",
    description: "Detecta colisiones con otros procesos por tipo o identificador.",
    syntax: "IF (id_col = collision(TYPE enemigo))\n  // colisión\nEND",
    insertText: "collision(TYPE )",
    categoryLabel: "Función DIV",
  },
  {
    name: "signal",
    type: "function",
    description: "Envía una señal de control a un proceso (s_kill, s_freeze, s_wakeup, s_sleep).",
    syntax: "signal(id_proceso, s_kill);",
    insertText: "signal(id, s_kill);",
    categoryLabel: "Función DIV",
  },
  {
    name: "let_me_alone",
    type: "function",
    description: "Elimina a todos los demás procesos en ejecución excepto al proceso actual.",
    syntax: "let_me_alone();",
    insertText: "let_me_alone();",
    categoryLabel: "Función DIV",
  },
  {
    name: "load_snd",
    type: "function",
    description: "Carga un fichero de sonido WAV/SND en memoria y devuelve su identificador.",
    syntax: "snd = load_snd(\"laser.wav\");",
    insertText: "load_snd(\"\")",
    categoryLabel: "Función DIV",
  },
  {
    name: "load_wav",
    type: "function",
    description: "Carga un archivo de audio WAV en memoria y devuelve su ID numérico.",
    syntax: "snd = load_wav(\"explosion.wav\");",
    insertText: "load_wav(\"\")",
    categoryLabel: "Función DIV",
  },
  {
    name: "load_pcm",
    type: "function",
    description: "Carga un fichero de audio PCM y devuelve su ID de sonido.",
    syntax: "snd = load_pcm(\"audio.pcm\");",
    insertText: "load_pcm(\"\")",
    categoryLabel: "Función DIV",
  },
  {
    name: "unload_wav",
    type: "function",
    description: "Libera de la memoria un sonido previamente cargado.",
    syntax: "unload_wav(id_sonido);",
    insertText: "unload_wav();",
    categoryLabel: "Función DIV",
  },
  {
    name: "unload_snd",
    type: "function",
    description: "Libera de la memoria un archivo de sonido.",
    syntax: "unload_snd(id_sonido);",
    insertText: "unload_snd();",
    categoryLabel: "Función DIV",
  },
  {
    name: "sound",
    type: "function",
    description: "Reproduce un sonido o efecto sintético (1..12 o cargado) y devuelve el canal activo.",
    syntax: "canal = sound(id_sonido, 100, 256);",
    insertText: "sound(1, 100, 256);",
    categoryLabel: "Función DIV",
  },
  {
    name: "sound_play",
    type: "function",
    description: "Alias de sound(): reproduce un sonido en un canal de audio.",
    syntax: "canal = sound_play(id_sonido, 100, 256);",
    insertText: "sound_play(1, 100, 256);",
    categoryLabel: "Función DIV",
  },
  {
    name: "stop_sound",
    type: "function",
    description: "Detiene un canal de sonido o todos los canales activos si no se indica canal.",
    syntax: "stop_sound(canal); // o stop_sound(); para silenciar todos",
    insertText: "stop_sound();",
    categoryLabel: "Función DIV",
  },
  {
    name: "sound_stop",
    type: "function",
    description: "Detiene la reproducción de un canal de audio o todos.",
    syntax: "sound_stop(canal);",
    insertText: "sound_stop();",
    categoryLabel: "Función DIV",
  },
  {
    name: "change_sound",
    type: "function",
    description: "Modifica el volumen y la frecuencia de un canal de sonido que esté reproduciéndose.",
    syntax: "change_sound(canal, nuevo_vol, nueva_freq);",
    insertText: "change_sound(canal, 100, 256);",
    categoryLabel: "Función DIV",
  },
  {
    name: "is_playing_sound",
    type: "function",
    description: "Comprueba si un canal de audio sigue en reproducción (1 si está activo, 0 si terminó).",
    syntax: "IF (is_playing_sound(canal))\n  // sigue reproduciéndose\nEND",
    insertText: "is_playing_sound()",
    categoryLabel: "Función DIV",
  },
  {
    name: "fade_sound",
    type: "function",
    description: "Aplica un fundido progresivo de volumen a un canal de sonido.",
    syntax: "fade_sound(canal, volumen_destino, velocidad);",
    insertText: "fade_sound(canal, 0, 10);",
    categoryLabel: "Función DIV",
  },
  {
    name: "set_volume",
    type: "function",
    description: "Ajusta el volumen maestro general (0 a 100).",
    syntax: "set_volume(80);",
    insertText: "set_volume(100);",
    categoryLabel: "Función DIV",
  },
  {
    name: "set_sound_volume",
    type: "function",
    description: "Ajusta el volumen de los efectos de sonido.",
    syntax: "set_sound_volume(80);",
    insertText: "set_sound_volume(100);",
    categoryLabel: "Función DIV",
  },
  {
    name: "set_music_volume",
    type: "function",
    description: "Ajusta el volumen de la música de fondo.",
    syntax: "set_music_volume(70);",
    insertText: "set_music_volume(80);",
    categoryLabel: "Función DIV",
  },
  {
    name: "load_song",
    type: "function",
    description: "Carga un tema musical en memoria (MOD, MIDI o sintético) y devuelve su ID.",
    syntax: "musica = load_song(\"musica.mod\");",
    insertText: "load_song(\"\")",
    categoryLabel: "Función DIV",
  },
  {
    name: "song",
    type: "function",
    description: "Reproduce una pista musical cargada con load_song.",
    syntax: "song(musica);",
    insertText: "song();",
    categoryLabel: "Función DIV",
  },
  {
    name: "stop_song",
    type: "function",
    description: "Detiene la música que se esté reproduciendo.",
    syntax: "stop_song();",
    insertText: "stop_song();",
    categoryLabel: "Función DIV",
  },
  {
    name: "load_fnt",
    type: "function",
    description: "Carga un tipo de letra FNT en memoria y devuelve su identificador de fuente.",
    syntax: "fuente = load_fnt(\"arcade.fnt\");",
    insertText: "load_fnt(\"\")",
    categoryLabel: "Función DIV",
  },
  {
    name: "unload_fnt",
    type: "function",
    description: "Libera de la memoria una fuente FNT previamente cargada.",
    syntax: "unload_fnt(fuente);",
    insertText: "unload_fnt();",
    categoryLabel: "Función DIV",
  },
  {
    name: "move_text",
    type: "function",
    description: "Mueve un texto en pantalla creado con write a una nueva posición (x, y).",
    syntax: "move_text(id_texto, nuevo_x, nuevo_y);",
    insertText: "move_text(id_texto, x, y);",
    categoryLabel: "Función DIV",
  },
  {
    name: "key",
    type: "function",
    description: "Comprueba si una tecla del teclado está actualmente pulsada.",
    syntax: "IF (key(_space))\n  // disparo\nEND",
    insertText: "key(_)",
    categoryLabel: "Función DIV",
  },
  {
    name: "write",
    type: "function",
    description: "Imprime un texto estático o dinámico en la pantalla.",
    syntax: "write(0, x, y, 4, \"Texto\");",
    insertText: "write(0, 100, 100, 0, \"\");",
    categoryLabel: "Función DIV",
  },
  {
    name: "write_int",
    type: "function",
    description: "Muestra en pantalla el valor de una variable entera en tiempo real.",
    syntax: "write_int(0, 10, 10, 0, OFFSET puntos);",
    insertText: "write_int(0, 10, 10, 0, OFFSET );",
    categoryLabel: "Función DIV",
  },
  {
    name: "delete_text",
    type: "function",
    description: "Elimina un texto en pantalla previamente creado con write.",
    syntax: "delete_text(id_texto); // o delete_text(all_text);",
    insertText: "delete_text(all_text);",
    categoryLabel: "Función DIV",
  },
  {
    name: "get_dist",
    type: "function",
    description: "Calcula la distancia euclidiana entre dos puntos (x1, y1) y (x2, y2).",
    syntax: "d = get_dist(x, y, x2, y2);",
    insertText: "get_dist(x, y, , )",
    categoryLabel: "Función DIV",
  },
  {
    name: "get_angle",
    type: "function",
    description: "Calcula el ángulo en milésimas de grado entre dos coordenadas.",
    syntax: "angle = get_angle(x, y, mouse.x, mouse.y);",
    insertText: "get_angle(x, y, , )",
    categoryLabel: "Función DIV",
  },
  {
    name: "advance",
    type: "function",
    description: "Avanza el proceso en la dirección de su ángulo actual.",
    syntax: "advance(velocidad);",
    insertText: "advance(4);",
    categoryLabel: "Función DIV",
  },
  {
    name: "xadvance",
    type: "function",
    description: "Modifica las coordenadas x e y según un ángulo y distancia dados.",
    syntax: "xadvance(angle, 5);",
    insertText: "xadvance(angle, );",
    categoryLabel: "Función DIV",
  },
  {
    name: "rand",
    type: "function",
    description: "Genera un número entero aleatorio comprendido entre un mínimo y un máximo.",
    syntax: "valor = rand(min, max);",
    insertText: "rand(1, 10)",
    categoryLabel: "Función DIV",
  },
  {
    name: "clear_screen",
    type: "function",
    description: "Limpia y borra el contenido del lienzo de pantalla.",
    syntax: "clear_screen();",
    insertText: "clear_screen();",
    categoryLabel: "Función DIV",
  },

  // VARIABLES DEL SISTEMA / LOCALES RESERVADAS
  {
    name: "graph",
    type: "variable",
    description: "Código numérico del gráfico del FPG asignado al proceso actual.",
    syntax: "graph = 1;",
    insertText: "graph",
    categoryLabel: "Variable local",
  },
  {
    name: "file",
    type: "variable",
    description: "Identificador del archivo FPG del que toma los gráficos el proceso.",
    syntax: "file = 0;",
    insertText: "file",
    categoryLabel: "Variable local",
  },
  {
    name: "x",
    type: "variable",
    description: "Coordenada horizontal X en píxeles del proceso.",
    syntax: "x += 2;",
    insertText: "x",
    categoryLabel: "Variable local",
  },
  {
    name: "y",
    type: "variable",
    description: "Coordenada vertical Y en píxeles del proceso.",
    syntax: "y += 2;",
    insertText: "y",
    categoryLabel: "Variable local",
  },
  {
    name: "z",
    type: "variable",
    description: "Profundidad de dibujado del proceso (Z-order: mayor Z se dibuja detrás).",
    syntax: "z = -10;",
    insertText: "z",
    categoryLabel: "Variable local",
  },
  {
    name: "angle",
    type: "variable",
    description: "Ángulo de rotación del proceso (0 a 360000 milésimas de grado).",
    syntax: "angle += 2000;",
    insertText: "angle",
    categoryLabel: "Variable local",
  },
  {
    name: "size",
    type: "variable",
    description: "Porcentaje de escalado o tamaño del gráfico (100 = 100% normal).",
    syntax: "size = 150;",
    insertText: "size",
    categoryLabel: "Variable local",
  },
  {
    name: "flags",
    type: "variable",
    description: "Banderas de renderizado del sprite (1 = espejo horizontal, 2 = espejo vertical).",
    syntax: "flags = 1;",
    insertText: "flags",
    categoryLabel: "Variable local",
  },
  {
    name: "alpha",
    type: "variable",
    description: "Nivel de transparencia del sprite (0 a 255).",
    syntax: "alpha = 180;",
    insertText: "alpha",
    categoryLabel: "Variable local",
  },
  {
    name: "id",
    type: "variable",
    description: "Identificador numérico único de la instancia del proceso actual.",
    syntax: "mi_id = id;",
    insertText: "id",
    categoryLabel: "Variable local",
  },
  {
    name: "father",
    type: "variable",
    description: "ID del proceso padre que creó la instancia actual.",
    syntax: "IF (father != 0) ... END",
    insertText: "father",
    categoryLabel: "Variable local",
  },
  {
    name: "mouse",
    type: "variable",
    description: "Estructura global del ratón (mouse.x, mouse.y, mouse.left, mouse.right).",
    syntax: "IF (mouse.left)\n  x = mouse.x;\nEND",
    insertText: "mouse",
    categoryLabel: "Variable global",
  },

  // CONSTANTES DEL SISTEMA
  {
    name: "s_kill",
    type: "constant",
    description: "Señal para eliminar y terminar inmediatamente un proceso.",
    syntax: "signal(id, s_kill);",
    insertText: "s_kill",
    categoryLabel: "Constante",
  },
  {
    name: "s_freeze",
    type: "constant",
    description: "Señal para congelar y pausar la ejecución de un proceso.",
    syntax: "signal(id, s_freeze);",
    insertText: "s_freeze",
    categoryLabel: "Constante",
  },
  {
    name: "s_wakeup",
    type: "constant",
    description: "Señal para reanudar un proceso previamente congelado o dormido.",
    syntax: "signal(id, s_wakeup);",
    insertText: "s_wakeup",
    categoryLabel: "Constante",
  },
  {
    name: "s_sleep",
    type: "constant",
    description: "Señal para pausar la ejecución manteniendo el gráfico en pantalla.",
    syntax: "signal(id, s_sleep);",
    insertText: "s_sleep",
    categoryLabel: "Constante",
  },
  {
    name: "_space",
    type: "constant",
    description: "Constante de la tecla Barra Espaciadora para la función key().",
    syntax: "IF (key(_space))",
    insertText: "_space",
    categoryLabel: "Constante tecla",
  },
  {
    name: "_enter",
    type: "constant",
    description: "Constante de la tecla Intro/Enter para la función key().",
    syntax: "IF (key(_enter))",
    insertText: "_enter",
    categoryLabel: "Constante tecla",
  },
  {
    name: "_up",
    type: "constant",
    description: "Constante de la tecla Flecha Arriba para la función key().",
    syntax: "IF (key(_up))",
    insertText: "_up",
    categoryLabel: "Constante tecla",
  },
  {
    name: "_down",
    type: "constant",
    description: "Constante de la tecla Flecha Abajo para la función key().",
    syntax: "_down",
    insertText: "_down",
    categoryLabel: "Constante tecla",
  },
  {
    name: "_left",
    type: "constant",
    description: "Constante de la tecla Flecha Izquierda para la función key().",
    syntax: "_left",
    insertText: "_left",
    categoryLabel: "Constante tecla",
  },
  {
    name: "_right",
    type: "constant",
    description: "Constante de la tecla Flecha Derecha para la función key().",
    syntax: "_right",
    insertText: "_right",
    categoryLabel: "Constante tecla",
  },
];
