import { VB3Form } from "../components/VB3/types";

export function getPresetFormDefinition(presetId?: string): VB3Form | null {
  if (!presetId) return null;

  switch (presetId) {
    case "app_landing":
    case "web_landing_generator":
      return {
        id: "frmLanding",
        name: "frmLanding",
        caption: "Nova Studio - Landing Page Moderna",
        backColor: "#0f172a",
        width: 600,
        height: 440,
        controls: [
          // Header / Navbar
          {
            id: "lblLogo",
            name: "lblLogo",
            type: "label",
            x: 20,
            y: 14,
            width: 200,
            height: 26,
            caption: "★ NOVA WEB BUILDER",
            enabled: true,
            visible: true,
          },
          {
            id: "btnInicio",
            name: "btnInicio",
            type: "commandbutton",
            x: 230,
            y: 12,
            width: 76,
            height: 28,
            caption: "Inicio",
            enabled: true,
            visible: true,
          },
          {
            id: "btnServicios",
            name: "btnServicios",
            type: "commandbutton",
            x: 312,
            y: 12,
            width: 86,
            height: 28,
            caption: "Servicios",
            enabled: true,
            visible: true,
          },
          {
            id: "btnPrecios",
            name: "btnPrecios",
            type: "commandbutton",
            x: 404,
            y: 12,
            width: 80,
            height: 28,
            caption: "Precios",
            enabled: true,
            visible: true,
          },
          {
            id: "btnContacto",
            name: "btnContacto",
            type: "commandbutton",
            x: 490,
            y: 12,
            width: 86,
            height: 28,
            caption: "Contacto",
            enabled: true,
            visible: true,
          },

          // Hero Section
          {
            id: "lblHeroTitle",
            name: "lblHeroTitle",
            type: "label",
            x: 24,
            y: 60,
            width: 550,
            height: 32,
            caption: "CREA TU SITIO WEB MODERNO CON WXDIV 3.0",
            enabled: true,
            visible: true,
          },
          {
            id: "lblHeroSub",
            name: "lblHeroSub",
            type: "label",
            x: 24,
            y: 96,
            width: 550,
            height: 24,
            caption: "Diseña visualmente con aceleración por GPU y exporta a Web, PWA o Android.",
            enabled: true,
            visible: true,
          },
          {
            id: "btnExplorar",
            name: "btnExplorar",
            type: "commandbutton",
            x: 24,
            y: 132,
            width: 160,
            height: 34,
            caption: "Explorar Funciones",
            enabled: true,
            visible: true,
          },
          {
            id: "btnVerPrecios",
            name: "btnVerPrecios",
            type: "commandbutton",
            x: 196,
            y: 132,
            width: 140,
            height: 34,
            caption: "Ver Precios",
            enabled: true,
            visible: true,
          },

          // Feature Highlights Cards
          {
            id: "lblCard1",
            name: "lblCard1",
            type: "label",
            x: 24,
            y: 184,
            width: 170,
            height: 60,
            caption: "⚡ ULTRA RÁPIDO\nSin lag. Acelerado con WebGL / HTML5 Canvas 60 FPS.",
            enabled: true,
            visible: true,
          },
          {
            id: "lblCard2",
            name: "lblCard2",
            type: "label",
            x: 206,
            y: 184,
            width: 170,
            height: 60,
            caption: "📱 TOUCH FIRST\nDiseñado para móviles, smartphones y tablets táctiles.",
            enabled: true,
            visible: true,
          },
          {
            id: "lblCard3",
            name: "lblCard3",
            type: "label",
            x: 388,
            y: 184,
            width: 186,
            height: 60,
            caption: "🤖 IA COPILOT\nGenera código, componentes y eventos en segundos.",
            enabled: true,
            visible: true,
          },

          // Lead Capture Section
          {
            id: "frameLead",
            name: "frameLead",
            type: "frame",
            x: 24,
            y: 260,
            width: 550,
            height: 120,
            caption: "Captación de Leads & Newsletter",
            enabled: true,
            visible: true,
          },
          {
            id: "lblEmailDesc",
            name: "lblEmailDesc",
            type: "label",
            x: 40,
            y: 290,
            width: 480,
            height: 20,
            caption: "Ingresa tu email para recibir invitaciones beta y actualizaciones:",
            enabled: true,
            visible: true,
          },
          {
            id: "txtEmailLead",
            name: "txtEmailLead",
            type: "textbox",
            x: 40,
            y: 316,
            width: 320,
            height: 30,
            text: "tu@empresa.com",
            caption: "Email",
            enabled: true,
            visible: true,
          },
          {
            id: "btnSuscribirme",
            name: "btnSuscribirme",
            type: "commandbutton",
            x: 372,
            y: 316,
            width: 170,
            height: 30,
            caption: "Suscribirme Gratis",
            enabled: true,
            visible: true,
          },
          {
            id: "lblStatusLead",
            name: "lblStatusLead",
            type: "label",
            x: 40,
            y: 354,
            width: 480,
            height: 18,
            caption: "✓ Sin tarjeta de crédito requerida • Cancelación instantánea",
            enabled: true,
            visible: true,
          },
        ],
      };

    case "app_todo":
    case "app_todo_store":
      return {
        id: "frmTodo",
        name: "frmTodo",
        caption: "Gestor de Tareas & Proyectos (Todo Pro)",
        backColor: "#0f172a",
        width: 560,
        height: 420,
        controls: [
          {
            id: "lblTodoTitle",
            name: "lblTodoTitle",
            type: "label",
            x: 24,
            y: 16,
            width: 340,
            height: 24,
            caption: "TASK MANAGER PRO - WXDIV MULTIPLATFORM",
            enabled: true,
            visible: true,
          },
          {
            id: "txtNuevaTarea",
            name: "txtNuevaTarea",
            type: "textbox",
            x: 24,
            y: 48,
            width: 340,
            height: 28,
            text: "Escribe una nueva tarea...",
            caption: "Tarea",
            enabled: true,
            visible: true,
          },
          {
            id: "btnAgregarTarea",
            name: "btnAgregarTarea",
            type: "commandbutton",
            x: 374,
            y: 48,
            width: 140,
            height: 28,
            caption: "+ Agregar Tarea",
            enabled: true,
            visible: true,
          },
          {
            id: "btnFiltroTodas",
            name: "btnFiltroTodas",
            type: "commandbutton",
            x: 24,
            y: 88,
            width: 100,
            height: 26,
            caption: "Todas (4)",
            enabled: true,
            visible: true,
          },
          {
            id: "btnFiltroCompletadas",
            name: "btnFiltroCompletadas",
            type: "commandbutton",
            x: 130,
            y: 88,
            width: 124,
            height: 26,
            caption: "Completadas (2)",
            enabled: true,
            visible: true,
          },
          {
            id: "btnFiltroPendientes",
            name: "btnFiltroPendientes",
            type: "commandbutton",
            x: 260,
            y: 88,
            width: 120,
            height: 26,
            caption: "Pendientes (2)",
            enabled: true,
            visible: true,
          },
          {
            id: "gridTareas",
            name: "gridTareas",
            type: "grid",
            x: 24,
            y: 124,
            width: 490,
            height: 220,
            caption: "Lista de Tareas",
            enabled: true,
            visible: true,
          },
          {
            id: "lblTodoFooter",
            name: "lblTodoFooter",
            type: "label",
            x: 24,
            y: 358,
            width: 490,
            height: 20,
            caption: "Estado: Almacén reactivo sincronizado con save_json y carga offline.",
            enabled: true,
            visible: true,
          },
        ],
      };

    case "app_login":
      return {
        id: "frmLogin",
        name: "frmLogin",
        caption: "Inicio de Sesión & Registro (Visual Basic 3.0)",
        backColor: "#c0c0c0",
        width: 460,
        height: 350,
        controls: [
          {
            id: "lblLoginHeader",
            name: "lblLoginHeader",
            type: "label",
            x: 32,
            y: 20,
            width: 380,
            height: 28,
            caption: "ACCESO AL SISTEMA WXDIV / AUTH",
            enabled: true,
            visible: true,
          },
          {
            id: "lblUserPrompt",
            name: "lblUserPrompt",
            type: "label",
            x: 32,
            y: 60,
            width: 150,
            height: 20,
            caption: "Nombre de Usuario / Email:",
            enabled: true,
            visible: true,
          },
          {
            id: "txtUsername",
            name: "txtUsername",
            type: "textbox",
            x: 32,
            y: 84,
            width: 380,
            height: 28,
            text: "admin@wxdiv.com",
            caption: "Usuario",
            enabled: true,
            visible: true,
          },
          {
            id: "lblPassPrompt",
            name: "lblPassPrompt",
            type: "label",
            x: 32,
            y: 124,
            width: 150,
            height: 20,
            caption: "Contraseña:",
            enabled: true,
            visible: true,
          },
          {
            id: "txtPassword",
            name: "txtPassword",
            type: "textbox",
            x: 32,
            y: 148,
            width: 380,
            height: 28,
            text: "••••••••",
            caption: "Password",
            enabled: true,
            visible: true,
          },
          {
            id: "chkRemember",
            name: "chkRemember",
            type: "checkbox",
            x: 32,
            y: 188,
            width: 220,
            height: 24,
            caption: "Recordar sesión en este equipo",
            enabled: true,
            visible: true,
          },
          {
            id: "btnDoLogin",
            name: "btnDoLogin",
            type: "commandbutton",
            x: 32,
            y: 232,
            width: 170,
            height: 34,
            caption: "Iniciar Sesión",
            enabled: true,
            visible: true,
          },
          {
            id: "btnCancelLogin",
            name: "btnCancelLogin",
            type: "commandbutton",
            x: 220,
            y: 232,
            width: 170,
            height: 34,
            caption: "Cancelar",
            enabled: true,
            visible: true,
          },
          {
            id: "lblForgotPass",
            name: "lblForgotPass",
            type: "label",
            x: 32,
            y: 286,
            width: 380,
            height: 20,
            caption: "¿Olvidaste tus credenciales? Recuperación con 2FA activa.",
            enabled: true,
            visible: true,
          },
        ],
      };

    case "app_dashboard":
      return {
        id: "frmDashboard",
        name: "frmDashboard",
        caption: "Dashboard Analítico Ejecutivo (KPIs & Métricas)",
        backColor: "#0f172a",
        width: 580,
        height: 440,
        controls: [
          {
            id: "lblDashHeader",
            name: "lblDashHeader",
            type: "label",
            x: 24,
            y: 16,
            width: 340,
            height: 24,
            caption: "DASHBOARD ANALÍTICO (MÉTRICAS & KPIs)",
            enabled: true,
            visible: true,
          },
          {
            id: "btnRefreshDash",
            name: "btnRefreshDash",
            type: "commandbutton",
            x: 420,
            y: 14,
            width: 120,
            height: 28,
            caption: "↻ Actualizar",
            enabled: true,
            visible: true,
          },
          {
            id: "lblKpiVentas",
            name: "lblKpiVentas",
            type: "label",
            x: 24,
            y: 56,
            width: 160,
            height: 60,
            caption: "VENTAS TOTALES\n$48,920.00 (+14% mes)",
            enabled: true,
            visible: true,
          },
          {
            id: "lblKpiUsers",
            name: "lblKpiUsers",
            type: "label",
            x: 200,
            y: 56,
            width: 160,
            height: 60,
            caption: "USUARIOS ACTIVOS\n1,428 En línea",
            enabled: true,
            visible: true,
          },
          {
            id: "lblKpiConv",
            name: "lblKpiConv",
            type: "label",
            x: 376,
            y: 56,
            width: 164,
            height: 60,
            caption: "TASA CONVERSIÓN\n4.2% (+0.8% semana)",
            enabled: true,
            visible: true,
          },
          {
            id: "gridTransacciones",
            name: "gridTransacciones",
            type: "grid",
            x: 24,
            y: 130,
            width: 516,
            height: 230,
            caption: "Registro de Transacciones y Clientes",
            enabled: true,
            visible: true,
          },
          {
            id: "lblDashFooter",
            name: "lblDashFooter",
            type: "label",
            x: 24,
            y: 374,
            width: 516,
            height: 20,
            caption: "Gráficos y tabulación acelerados con Canvas 2D • WXDIV Analytics Engine",
            enabled: true,
            visible: true,
          },
        ],
      };

    case "app_crm":
    case "app_database_sqlite":
      return {
        id: "frmCrm",
        name: "frmCrm",
        caption: "Gestión de Clientes & Base de Datos SQLite",
        backColor: "#c0c0c0",
        width: 580,
        height: 440,
        controls: [
          {
            id: "lblCrmHeader",
            name: "lblCrmHeader",
            type: "label",
            x: 24,
            y: 16,
            width: 320,
            height: 24,
            caption: "BASE DE DATOS SQLITE - CLIENTES CRM",
            enabled: true,
            visible: true,
          },
          {
            id: "lblNombre",
            name: "lblNombre",
            type: "label",
            x: 24,
            y: 48,
            width: 80,
            height: 20,
            caption: "Cliente:",
            enabled: true,
            visible: true,
          },
          {
            id: "txtNombre",
            name: "txtNombre",
            type: "textbox",
            x: 90,
            y: 46,
            width: 160,
            height: 26,
            text: "Carlos Perez",
            caption: "Nombre",
            enabled: true,
            visible: true,
          },
          {
            id: "lblEmpresa",
            name: "lblEmpresa",
            type: "label",
            x: 260,
            y: 48,
            width: 80,
            height: 20,
            caption: "Empresa:",
            enabled: true,
            visible: true,
          },
          {
            id: "txtEmpresa",
            name: "txtEmpresa",
            type: "textbox",
            x: 330,
            y: 46,
            width: 140,
            height: 26,
            text: "Nexus Dev",
            caption: "Empresa",
            enabled: true,
            visible: true,
          },
          {
            id: "btnGuardarCliente",
            name: "btnGuardarCliente",
            type: "commandbutton",
            x: 480,
            y: 44,
            width: 80,
            height: 28,
            caption: "Guardar",
            enabled: true,
            visible: true,
          },
          {
            id: "gridClientes",
            name: "gridClientes",
            type: "grid",
            x: 24,
            y: 86,
            width: 536,
            height: 280,
            caption: "Tabla de Clientes SQLite",
            enabled: true,
            visible: true,
          },
          {
            id: "btnExportSql",
            name: "btnExportSql",
            type: "commandbutton",
            x: 24,
            y: 380,
            width: 140,
            height: 30,
            caption: "Exportar .SQL",
            enabled: true,
            visible: true,
          },
          {
            id: "lblStatusSql",
            name: "lblStatusSql",
            type: "label",
            x: 180,
            y: 386,
            width: 380,
            height: 20,
            caption: "Conectado a empresas.db (SQLite In-Memory). 3 registros activos.",
            enabled: true,
            visible: true,
          },
        ],
      };

    case "app_calculator_sci":
      return {
        id: "frmCalc",
        name: "frmCalc",
        caption: "Calculadora Estándar (Calc WXDIV)",
        backColor: "#c0c0c0",
        width: 360,
        height: 420,
        controls: [
          {
            id: "txtPantalla",
            name: "txtPantalla",
            type: "textbox",
            x: 20,
            y: 20,
            width: 320,
            height: 40,
            text: "0",
            caption: "Display",
            enabled: true,
            visible: true,
          },
          { id: "btn7", name: "btn7", type: "commandbutton", x: 20, y: 70, width: 68, height: 48, caption: "7", enabled: true, visible: true },
          { id: "btn8", name: "btn8", type: "commandbutton", x: 104, y: 70, width: 68, height: 48, caption: "8", enabled: true, visible: true },
          { id: "btn9", name: "btn9", type: "commandbutton", x: 188, y: 70, width: 68, height: 48, caption: "9", enabled: true, visible: true },
          { id: "btnDiv", name: "btnDiv", type: "commandbutton", x: 272, y: 70, width: 68, height: 48, caption: "/", enabled: true, visible: true },

          { id: "btn4", name: "btn4", type: "commandbutton", x: 20, y: 130, width: 68, height: 48, caption: "4", enabled: true, visible: true },
          { id: "btn5", name: "btn5", type: "commandbutton", x: 104, y: 130, width: 68, height: 48, caption: "5", enabled: true, visible: true },
          { id: "btn6", name: "btn6", type: "commandbutton", x: 188, y: 130, width: 68, height: 48, caption: "6", enabled: true, visible: true },
          { id: "btnMul", name: "btnMul", type: "commandbutton", x: 272, y: 130, width: 68, height: 48, caption: "*", enabled: true, visible: true },

          { id: "btn1", name: "btn1", type: "commandbutton", x: 20, y: 190, width: 68, height: 48, caption: "1", enabled: true, visible: true },
          { id: "btn2", name: "btn2", type: "commandbutton", x: 104, y: 190, width: 68, height: 48, caption: "2", enabled: true, visible: true },
          { id: "btn3", name: "btn3", type: "commandbutton", x: 188, y: 190, width: 68, height: 48, caption: "3", enabled: true, visible: true },
          { id: "btnSub", name: "btnSub", type: "commandbutton", x: 272, y: 190, width: 68, height: 48, caption: "-", enabled: true, visible: true },

          { id: "btn0", name: "btn0", type: "commandbutton", x: 20, y: 250, width: 68, height: 48, caption: "0", enabled: true, visible: true },
          { id: "btnDot", name: "btnDot", type: "commandbutton", x: 104, y: 250, width: 68, height: 48, caption: ".", enabled: true, visible: true },
          { id: "btnIgual", name: "btnIgual", type: "commandbutton", x: 188, y: 250, width: 68, height: 48, caption: "=", enabled: true, visible: true },
          { id: "btnAdd", name: "btnAdd", type: "commandbutton", x: 272, y: 250, width: 68, height: 48, caption: "+", enabled: true, visible: true },

          { id: "btnClear", name: "btnClear", type: "commandbutton", x: 20, y: 310, width: 152, height: 44, caption: "C (Limpiar)", enabled: true, visible: true },
          { id: "btnMem", name: "btnMem", type: "commandbutton", x: 188, y: 310, width: 152, height: 44, caption: "M+ (Memoria)", enabled: true, visible: true },
        ],
      };

    case "app_vb_forms":
      return {
        id: "form1",
        name: "Form1",
        caption: "Form1 - Panel de Control & Clientes",
        backColor: "#c0c0c0",
        width: 560,
        height: 440,
        controls: [
          {
            id: "btnClientes",
            name: "btnClientes",
            type: "commandbutton",
            x: 20,
            y: 20,
            width: 130,
            height: 32,
            caption: "📄 Form Clientes",
            enabled: true,
            visible: true,
          },
          {
            id: "btnStats",
            name: "btnStats",
            type: "commandbutton",
            x: 160,
            y: 20,
            width: 140,
            height: 32,
            caption: "📊 Form Estadísticas",
            enabled: true,
            visible: true,
          },
          {
            id: "btnConfig",
            name: "btnConfig",
            type: "commandbutton",
            x: 310,
            y: 20,
            width: 150,
            height: 32,
            caption: "⚙️ Form Configuración",
            enabled: true,
            visible: true,
          },
          {
            id: "gridClientesVb",
            name: "gridClientesVb",
            type: "grid",
            x: 20,
            y: 68,
            width: 516,
            height: 280,
            caption: "Tabla de Clientes",
            enabled: true,
            visible: true,
          },
          {
            id: "lblVbStatus",
            name: "lblVbStatus",
            type: "label",
            x: 20,
            y: 364,
            width: 516,
            height: 20,
            caption: "Estado: Conectado a DIV Database Engine. 4 registros activos.",
            enabled: true,
            visible: true,
          },
        ],
      };

    case "app_text_editor":
      return {
        id: "frmNotepad",
        name: "frmNotepad",
        caption: "Notepad WXDIV - Editor de Texto MDI",
        backColor: "#c0c0c0",
        width: 580,
        height: 440,
        controls: [
          {
            id: "btnNuevo",
            name: "btnNuevo",
            type: "commandbutton",
            x: 16,
            y: 12,
            width: 80,
            height: 28,
            caption: "📄 Nuevo",
            enabled: true,
            visible: true,
          },
          {
            id: "btnAbrir",
            name: "btnAbrir",
            type: "commandbutton",
            x: 102,
            y: 12,
            width: 80,
            height: 28,
            caption: "📂 Abrir",
            enabled: true,
            visible: true,
          },
          {
            id: "btnGuardar",
            name: "btnGuardar",
            type: "commandbutton",
            x: 188,
            y: 12,
            width: 86,
            height: 28,
            caption: "💾 Guardar",
            enabled: true,
            visible: true,
          },
          {
            id: "txtDocumento",
            name: "txtDocumento",
            type: "textbox",
            x: 16,
            y: 50,
            width: 548,
            height: 340,
            text: "Bienvenido a Notepad WXDIV.\nPuedes redactar texto, código DIV, y procesar scripts.\nSoporta eventos de teclado, edición en tiempo real y exportación.",
            caption: "Área de texto",
            enabled: true,
            visible: true,
          },
          {
            id: "lblNotepadStatus",
            name: "lblNotepadStatus",
            type: "label",
            x: 16,
            y: 400,
            width: 548,
            height: 22,
            caption: "Líneas: 3 | Columnas: 52 | Codificación: UTF-8 | WXDIV 3.0",
            enabled: true,
            visible: true,
          },
        ],
      };

    case "app_paint_canvas":
      return {
        id: "frmPaint",
        name: "frmPaint",
        caption: "Paint 2D Canvas - Dibujo VGA",
        backColor: "#c0c0c0",
        width: 600,
        height: 440,
        controls: [
          {
            id: "picCanvas",
            name: "picCanvas",
            type: "picturebox",
            x: 110,
            y: 16,
            width: 470,
            height: 380,
            caption: "Lienzo de dibujo",
            enabled: true,
            visible: true,
          },
          {
            id: "btnLapiz",
            name: "btnLapiz",
            type: "commandbutton",
            x: 16,
            y: 16,
            width: 80,
            height: 30,
            caption: "✏️ Lápiz",
            enabled: true,
            visible: true,
          },
          {
            id: "btnPincel",
            name: "btnPincel",
            type: "commandbutton",
            x: 16,
            y: 52,
            width: 80,
            height: 30,
            caption: "🖌️ Pincel",
            enabled: true,
            visible: true,
          },
          {
            id: "btnBorrador",
            name: "btnBorrador",
            type: "commandbutton",
            x: 16,
            y: 88,
            width: 80,
            height: 30,
            caption: "🧹 Borrador",
            enabled: true,
            visible: true,
          },
          {
            id: "shpRect",
            name: "shpRect",
            type: "shape",
            x: 16,
            y: 126,
            width: 80,
            height: 40,
            caption: "Rectángulo",
            shapeType: "rect",
            enabled: true,
            visible: true,
          },
          {
            id: "lblPaintStatus",
            name: "lblPaintStatus",
            type: "label",
            x: 16,
            y: 408,
            width: 564,
            height: 20,
            caption: "Herramienta: Lápiz • Color: Negro • Canvas: 470x380 px",
            enabled: true,
            visible: true,
          },
        ],
      };

    case "game_arcade_canvas":
      return {
        id: "frmArcade",
        name: "frmArcade",
        caption: "Juego Arcade 2D - ActiveX Canvas",
        backColor: "#050811",
        width: 600,
        height: 450,
        controls: [
          {
            id: "picGame",
            name: "picGame",
            type: "picturebox",
            x: 16,
            y: 16,
            width: 440,
            height: 380,
            caption: "Canvas Arcade 60 FPS",
            enabled: true,
            visible: true,
          },
          {
            id: "lblScore",
            name: "lblScore",
            type: "label",
            x: 470,
            y: 16,
            width: 110,
            height: 30,
            caption: "SCORE: 0000",
            foreColor: "#ffff00",
            enabled: true,
            visible: true,
          },
          {
            id: "btnStartGame",
            name: "btnStartGame",
            type: "commandbutton",
            x: 470,
            y: 60,
            width: 110,
            height: 36,
            caption: "▶ Iniciar",
            enabled: true,
            visible: true,
          },
          {
            id: "btnResetGame",
            name: "btnResetGame",
            type: "commandbutton",
            x: 470,
            y: 104,
            width: 110,
            height: 36,
            caption: "🔄 Reiniciar",
            enabled: true,
            visible: true,
          },
          {
            id: "gaugeEnergy",
            name: "gaugeEnergy",
            type: "gauge",
            x: 470,
            y: 154,
            width: 110,
            height: 26,
            caption: "Energía",
            value: 80,
            enabled: true,
            visible: true,
          },
        ],
      };

    default:
      // Any other preset with "app_" or "web_" prefix gets an initial clean editable form
      if (presetId.startsWith("app_") || presetId.startsWith("web_")) {
        return {
          id: `frm_${presetId}`,
          name: `Form1`,
          caption: `Formulario - ${presetId}`,
          backColor: "#c0c0c0",
          width: 560,
          height: 440,
          controls: [
            {
              id: "cmd1",
              name: "Command1",
              type: "commandbutton",
              x: 24,
              y: 24,
              width: 120,
              height: 32,
              caption: "Aceptar",
              enabled: true,
              visible: true,
            },
            {
              id: "txt1",
              name: "Text1",
              type: "textbox",
              x: 24,
              y: 72,
              width: 240,
              height: 26,
              caption: "Texto",
              text: "Datos del formulario",
              enabled: true,
              visible: true,
            },
            {
              id: "lbl1",
              name: "Label1",
              type: "label",
              x: 24,
              y: 114,
              width: 240,
              height: 20,
              caption: "Etiqueta descriptiva",
              enabled: true,
              visible: true,
            },
          ],
        };
      }
      return null;
  }
}
